# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres : lastest
    restart: always
  
    environment:
      POSTGRES_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}

  
    ports:
      - "5432":"5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data